### ISSUE TITLE
Suggest ID from multiple ranges

### ISSUE THREAD

**Issue by kaspermoerch** [vjekob/al-objid#11]
### Scenario
You are working on a project where you have multiple id ranges in app.json. This could be e.g. if you code your app and tests in the same app and then remove the tests in a build pipeline or maybe you have multiple ranges assigned to your app.

### The problem
When assigning a new id AL Object ID Ninja suggest the first available ID. If I want to assign an ID from another range, I need to do that manually and then synchronize with AL Object ID Ninja backend.

### The solution
AL Object ID Ninja should suggest the first available id from all the ranges in app.json.

**Comment by vjekob** [comment]
This is probably going to be a configuration setting where you can switch this behavior on or off. If on, it would offer you multiple IDs and it would only commit the one from the range you choose.

What would you have it do when for example you explicitly choose a number from a range, but by the time you select that number in the dropdown list it is already unavailable (assigned to someone else) and there are no more numbers left in that sub-range?

**Comment by vjekob** [comment]
This feature is now released in 2.4.0.

More details: https://github.com/vjekob/al-objid/commit/49119425cf935306b031b7551685b533d1927c01
