### ISSUE TITLE
Range Explorer : Collapse / Expand All icon (Nice to have)

### ISSUE THREAD

**Issue by fvet** [vjekob/al-objid#18]
When gradually activating Object ID Ninja on our apps, the 'Range Explorer' is growing rapidly. I'd be nice if we could have a 'Collapse (-) / Expand (+)' icon - similar to the Source Control pane - to hide / show range details per app.

![image](https://user-images.githubusercontent.com/25268332/137810364-cbf1f3c5-a7c4-43da-9e20-ca7560910577.png)

![image](https://user-images.githubusercontent.com/25268332/137810593-a8ec99a0-30f6-4023-846b-0c46f9a2bf96.png)

**Comment by vjekob** [comment]
Unfortunately, I'll have to close this with "wontfix" label. There is no API that allows this. The closest I could get is `showCollapseAll` which indeed adds the collapse all button, but it doesn't flip between collapse/expand once collapsed. The only place where this is documented is this: https://github.com/microsoft/vscode/issues/62073

So, until Microsoft expands (no pun intended 😁) their API, this issue will stay closed. Sorry for the inconvenience.

**Comment by vjekob** [comment]
I am actually reopening this. With the new range explorer coming up in the next version this functionality was really needed (a lot of nodes present). So, I have figured out a way how to get around the VS Code API limitation.

Long story short, this feature is coming in the next release (2.7.0).

**Comment by vjekob** [comment]
There you go: https://github.com/vjekob/al-objid/commit/4318a58260e731643ab4db2915573b8e2a1bb649

**Comment by TCI-Radek** [comment]
Somehow related to this nice feature...
Could you add a way to export range explorer information to CSV file?
Sometimes we need to discuss/report/analyze the utilization of ranges in the meetings where using VSC is not easy - and it would be great to be able to export this and be able to convert it into some nice slides...

**Comment by vjekob** [comment]
> Somehow related to this nice feature... Could you add a way to export range explorer information to CSV file? Sometimes we need to discuss/report/analyze the utilization of ranges in the meetings where using VSC is not easy - and it would be great to be able to export this and be able to convert it into some nice slides...

Absolutely, but let's keep it one topic per issue, shall we? This issue is about collapsing/expanding. If you have a feature request, then please just create another issue and it will be so much easier for everyone (you and me both included) to track the progress 😉

**Comment by vjekob** [comment]
Delivered in v2.7.0
