### ISSUE TITLE
Feature: Cross Partners Object ID assignment

### ISSUE THREAD

**Issue by dkatson** [vjekob/al-objid#19]
Currently, when AL repo is synched with the Azure backend, the under the AppId there is the storage of all used and available id's per this app. 

What if to add a tenant and environment from launch.json or better as a separate Ninja configuration (pointing to a production tenant and environment), where PTE will be installed. 

If 2+ partners, or even 1 partner with several cooking PTE's will point to the same environment, then service can suggest new range, or at least notify that the chosen range will conflict with other extension. 

This will automatically give everyone a value of reducing the risk having same id used in different pte’s even from different partners!

**Comment by vjekob** [comment]
Hi Dmitry,

Would the app pool feature (https://github.com/vjekob/al-objid/issues/1) satisfy this requirement? App pools don't need to belong to a single partner and any app that joins an existing pool will share the same object IDs.

Please consider this and let me know.

**Comment by vjekob** [comment]
I believe that this is solved with the app pool feature of v2.5.0

Please check the release notes here: https://github.com/vjekob/al-objid/blob/master/vscode-extension/docs/ReleaseNotes.v2.5.0.md

Try it out, and if you think it does not satisfy your need, let me know and I'll reopen this issue.

**Comment by dkatson** [comment]
Thanks, @vjekob . We will try this out
