### ISSUE TITLE
Suggested Field ID in tableextension starts from 1

### ISSUE THREAD

**Issue by kaspermoerch** [vjekob/al-objid#20]
When I create a tableextension the suggested field id is 1:

![image](https://user-images.githubusercontent.com/1166791/146151740-e0e13e00-08b8-4de0-a10a-4e4bd94f4fd7.png)

Field ids in tableextensions should be suggested from the id range(s) provided in app.json.

**Comment by pri-kise** [comment]
I have the same problem for enum extensions. They start by 1

**Comment by DavidFeldhoff** [comment]
Any news here?

**Comment by vjekob** [comment]
I've seen this, yeah, and I have to check it. I'll be working a bit on Ninja in the following days, so expect the fix to arrive at some point next week.

**Comment by vjekob** [comment]
This problem is solved. It was a back-end issue so no update to Ninja front-end (VS Code extension) is needed.

https://github.com/vjekob/al-objid/commit/0f3c696d8544b91e7683f2b50d30db67fd1fbd04
