### ISSUE TITLE
Assign Enum object ID action missing if the enum is already named 

### ISSUE THREAD

**Issue by tinestaric** [vjekob/al-objid#23]
Noticed a small bug on v2.2.0 when trying to assign an Enum object ID to an enum I have already named. 
![image](https://user-images.githubusercontent.com/42935028/147055321-b87e5b76-8431-4c67-8c06-ffb9c3c80147.png)

if the Enum is not named yet, it works fine. 

It also works fine with the v2.1.3
![image](https://user-images.githubusercontent.com/42935028/147055611-b08e95bc-0f49-4dd2-9134-6cf762e959d7.png)

**Comment by vjekob** [comment]
Strange one, really. I'll have to check this. Seems like a parser issue. Good catch!

**Comment by vjekob** [comment]
I've fixed this, and it will be released as a part of 2.3.0. Commit: https://github.com/vjekob/al-objid/commit/cbf3b7753d8ddc9f695ff0b79ce9c52121f8e2d6
