### ISSUE TITLE
Enhancement: Push notifications instead of polling

### ISSUE THREAD

**Issue by vjekob** [vjekob/al-objid#3]
# Problem

Right now (v1.0.3) notifications are being pulled from the back end with polling interval of 15 seconds. This is poor man's approach, but to make this cool feature work in time for yesterday's beerinar demo, I had to hack something quickly.

Needless to say, this can't stay that way.

# Possible approaches

I looked at some frameworks, but haven't really figured out anything useful just yet.

If you have an idea about which push notifications framework I should use, do let me know.

These are requirements:
* It must be absolutely free to use (or if it costs $, then it must be part of Azure stack and count towards Azure consumption)
* It must work on nodejs client-side.

Any ideas?

**Comment by martonsagi** [comment]
I would give [Azure Event Grid](https://docs.microsoft.com/en-us/azure/event-grid/overview) a try. [Pricing](https://azure.microsoft.com/en-us/pricing/details/event-grid/) seems low-cost for this purpose.

Disclaimer: I did not use it before, but this is what I'd use for myself. :-)

**Comment by vjekob** [comment]
The problem is not pushing events from my Azure Functions back end - that's the easy part. The problem is consuming events from nodejs. There is nothing that Azure Event Grid can push events to that can be consumed with a ready-made nodejs client library, at least from what I could find so far.

But thanks for the hint, when I focus on this feature, I'll investigate deeper.

**Comment by martonsagi** [comment]
Perhaps Service Bus could work, that has a connection string that you can connect to from clients. Although, based on the examples, it's still like an endless loop to get updates, not specifically event-based. A tiny step away from a timer :D

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-nodejs-how-to-use-queues

**Comment by vjekob** [comment]
From the example it seems that this is actual tunnel/socket thing, not a polling thing. The example at that page gives 2s delay to stop processing just because it's a demo, but if I'd connect to the bus from a `Disposable` and then disconnect from its `dispose` it could easily work.

The only problem is that queue is first-come-first served. If I have fifteen clients to notify, only the first to fetch the message from the queue would actually get notified...

So... back to square one, really. I'll investigate deeper about Event Grid, there must be something I can use from there.

**Comment by vjekob** [comment]
I am closing this. There won't be anything but polling for the foreseeable future. All other options are going to cost more as far as I can tell from checking the pricing options available. Also, third-party options are going to cost a lot more. Unfortunately, for a free service, I have to keep costs down. So that's it.

At some future point I may do a peer-to-peer notification system, that would make sense, even though it would require some local configuration.

So, for now, that's it. Case closed.
