### ISSUE TITLE
[Idea] Optional Object Type for Logical IdRanges

### ISSUE THREAD

**Issue by pri-kise** [vjekob/al-objid#30]
We sometimes want to use differnt Object Id Range for our apps. Especially for Page Extensions.
Since we can't set this in the app.json, maybe this can be added to the logical ID Ranges, that you added recently.

**Comment by vjekob** [comment]
I have actually already thought about this, and plan on releasing this at some point. Right now (work in progress, but you can follow it in the repo) I support only "idRanges" in `.objidconfig`, but I plan to do an additional setting called `objectRanges` where you would be able to define different logical ranges for different object types (e.g. for tables, "Sales" range is 50000..50010 but for codeunits "Sales" range is 50000..50050.

Is this what you had in mind, too?

**Comment by pri-kise** [comment]
@vjekob Yes that's exactly what I had in mind.
I'm already following the deveolpment of this repo by giving it a star.

**Comment by vjekob** [comment]
This feature is now provided in v2.6.0. Let me know how you like it!
