### ISSUE TITLE
Range explorer is missing range description 

### ISSUE THREAD

**Issue by NKarolak** [vjekob/al-objid#31]
First of all: the logical range feature helps me so much, thanks a lot for that!

I don't know whether it's a bug or feature, but in my case, the range description is missing for my test app (in yellow):
![image](https://user-images.githubusercontent.com/34504100/167108145-582df972-ca72-41e3-9fb7-bc2a3553d1c9.png)

You're seeing a workspace with (main) app and test app. 
The range descriptions for the main app are displayed, but the only one from the test app is not.

**Comment by vjekob** [comment]
Definitely a bug. I'll need to take a look at this.

**Comment by vjekob** [comment]
Fixed in v2.7.0
