### ISSUE TITLE
Export range explorer information into CSV/XML

### ISSUE THREAD

**Issue by TCI-Radek** [vjekob/al-objid#33]
Could you, please, add a way to export range explorer information to CSV file? Sometimes we need to discuss/report/analyze the utilization of ranges in the meetings where using VSC is not easy - and it would be great to be able to export this and be able to convert it into some nice slides...

**Comment by vjekob** [comment]
Sure, this is a cool feature request.

**Comment by vjekob** [comment]
Resolved with https://github.com/vjekob/al-objid/commit/2be3b2d26a153bbaeb5008dbc1a3bfad783dbeff

Will be released with 2.11.0
