### ISSUE TITLE
Enhancement: Add Ids (in stead of syncing)

### ISSUE THREAD

**Issue by waldo1001** [vjekob/al-objid#4]
### Problem
To be able to go live with this tool, I can imagine in project with ongoing development, multiple branches might already have reserved id's on top of the main branch

### Solution
new function "Add Id" that's similar to sync, but doesn't remove any ids, just adds missing ones.

### Even better
Cycle through all branches.  Like:
- loop all REMOTE branches
- make sure to pull the latest versions
- **Add** all missing ids to the backend

**Comment by vjekob** [comment]
This is a cool feature request! Especially looping through branches. This is coming next week.

**Comment by vjekob** [comment]
Back end now supports PATCH requests which will update existing object ID consumption, rather than replacing it.

This will be released as v1.1.0 later today

**Comment by vjekob** [comment]
Version 1.1.0 contains this feature. You can now run either merge or replace synchronization. Check https://vjeko.com/2021/09/13/al-object-id-ninja-v1-1-0-released/
