### ISSUE TITLE
Id's of .al files with UTF-16 encoding are not synced

### ISSUE THREAD

**Issue by TeusV** [vjekob/al-objid#46]
Object ID Ninja suggested IDs that were not free. Turns out that I have some .al files with UTF-16 LE and for these files the object ids are not synced. I don't know why these files had UTF-16 encoding and I'm going to change it to UTF-8, I'm just reporting this in case you would like to know.

**Comment by vjekob** [comment]
This is interesting. I wasn't paying attention to encoding, and it could be that the parser fails because it does indeed read files as UTF-8.

I wonder how you got them to be UTF-16... 🤔

**Comment by TeusV** [comment]
Yes I wondered about that too :) They were all extension objects, we might have the ForNav txt to AL convertor to blame.

**Comment by vjekob** [comment]
Ok, then if you don't mind, I'll close this issue as "wontfix". Normal AL files are all UTF-8, and this is actually a ForNav issue that should be reported to them.
