### ISSUE TITLE
Bug: Licensed object shown as not in license

### ISSUE THREAD

**Issue by petertijsma** [vjekob/al-objid#47]
Even though an object is obsoleted, Ninja shows it as not in the license:

![image](https://user-images.githubusercontent.com/86952584/191791082-9268d36e-893c-413a-910f-d31320cd994b.png)

![image](https://user-images.githubusercontent.com/86952584/191791730-7a9671d3-ca9d-4779-818e-6a81f560263b.png)

**Comment by vjekob** [comment]
Fixed in release 2.10.0 (to be released this week)
