### ISSUE TITLE
[Feature] - Check License stored in SharePoint

### ISSUE THREAD

**Issue by dral77** [vjekob/al-objid#48]
I'm posting it as a feature request.
Would it be possible that instead od Workspace(Git Repo) extension has a setting to check the license that resides on SharePoint ?
Regards, 
Aleksandar.

**Comment by vjekob** [comment]
Honestly, I don't think this is going to happen, at least I won't do it myself. I don't see much use for it, this is a very specific edge case that a very few users would use.

I could add a setting that allows you to read a license from any path, not necessarily from within the repository.

Last, feel free to create a pull request for this feature if you really need it.
