### ISSUE TITLE
Info: Runtime version 3.0 runs out of support 03.12.2022 (what ever that means)

### ISSUE THREAD

**Issue by KristofKlein** [vjekob/al-objid#49]
Hi,

not sure if you have seen this (I bet you did): 

https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-csharp

At least I get a warning in Azure on that topic for the AL Ninja Azure Functions.

**Comment by vjekob** [comment]
I assume you are running on your own back-end. You can just change runtime to 4, and problem solved. There is nothing in particular that Ninja back-end uses that specifically depends on anything in 3 or 4.
