### ISSUE TITLE
License Check cannot deal with relative path one level up

### ISSUE THREAD

**Issue by pri-kise** [vjekob/al-objid#52]
At first I have placed the license file in the Project Folder instead of the MainApp Folder. Therefore I specified a path like the following:

```json
{
  "bcLicense": "../CustomerLicence.bclicense",
  "idRanges": [],
  "objectRanges": {

    ]
  }
}
```

I received no warning or error, but when I checked the developer tools, there was the following error:

> TypeError: Cannot read properties of undefined (reading 'uri')
> 	at new BCLicense (c:\Users\kise\.vscode\extensions\vjeko.vjeko-al-objid-2.9.1\out\lib\BCLicense.js:36:83)
> 	at ObjIdConfigLinter.<anonymous> (c:\Users\kise\.vscode\extensions\vjeko.vjeko-al-objid-2.9.1\out\features\linters\ObjIdConfigLinter.js:211:29)
> 	at Generator.next (<anonymous>)
> 	at fulfilled (c:\Users\kise\.vscode\extensions\vjeko.vjeko-al-objid-2.9.1\out\features\linters\ObjIdConfigLinter.js:5:58)
> 	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> $onExtensionRuntimeError @ mainThreadExtensionService.ts:80

**Comment by vjekob** [comment]
This will be included in 2.10.0
