### ISSUE TITLE
Synchronize App Ids for multiple apps

### ISSUE THREAD

**Issue by Brom28** [vjekob/al-objid#56]
Hello,

I have a question. Is it possible or planned for the future to share the same id range for multiple Extensions.

### For Example:

- App A has an id range 50100 to 50199
- App B has an id range 50100 to 50199 too

Can I connect this two Extensions to share the same id range without Id conflicts?

**Comment by vjekob** [comment]
Yes, this is already supported. The feature is called "App pools"

https://github.com/vjekob/al-objid/blob/master/vscode-extension/docs/app-pools.md
