### ISSUE TITLE
"Finding objects" in appPool never finish

### ISSUE THREAD

**Issue by jensthomsenEV** [vjekob/al-objid#57]
Hello,

I have a setup with 3 apps in a repos. With 2 of the apps I want to be able to share the object ID, so I have created an AppPool with them.  But I cant get them in sync with the azure backend?? The last thing i tried was the interactive sync, where I pointed one branch (Develop) out in each app to be synched. But the syncronization never get finished, it just keeps saying "Finding objects IDs in...."

**Comment by vjekob** [comment]
I am afraid that I don't have enough info to be able to tell you what's going on.

What you could do:
- Turn on verbose logging for your workspace (setting "Object ID Ninja: Use Verbose Output Logging")
- Provide me with the output from "AL Object ID Ninja" output window

Thanks!

**Comment by vjekob** [comment]
I retried this a few times more with a few setups, and couldn't repeat this.

Please update to 2.10.0 when it becomes available, and try to see if this issue persist. If so, share the app pool ID with me (send it to me as a private message on twitter at @vjekob) and I'll look into what could be causing it. Until then, I'm closing this issue.

**Comment by jensthomsenEV** [comment]
Hi Vjeko

Thx for taking time to answering my question:-) 

Object Ninja is a fantastic tool, the only "problem" is, that it has become indispensable for AL developers, so whenever there is a small problem we're f...:-) but GREAT tool, and amazing that you're taking time to build/fix it. 

I will try you're suggestions to my problem out, and if I still have issues I will return
