### ISSUE TITLE
Confusing Actions/Commands - Reclaim Object Id / Store ID assignment

### ISSUE THREAD

**Issue by pri-kise** [vjekob/al-objid#60]
If i open the command view an search for ninja, then I receive confusing commands, that I can't differentiate.

![image](https://user-images.githubusercontent.com/56249171/232981862-da3aac8a-9a3e-4d6a-bdac-8b1ba7b8b5cb.png)

**Comment by vjekob** [comment]
This is fixed in 2.11.1 that will be released today.
