### ISSUE TITLE
Enhancement: Support both app.json elements idRange and idRanges

### ISSUE THREAD

**Issue by ps610** [vjekob/al-objid#7]
First of all, thank you for your work on this great extension. 🙂

### Problem

If the app.json contains the element "idRange" instead of the required "idRanges" the API requests are failing because of the missing range property.

### Solution

Since both elements are allowed, the extension should also support both.

**Comment by vjekob** [comment]
I'll treat this as a bug. Even though `idRange` is deprecated since v4.0 of runtime, Ninja wants to support as many versions as technically possible. This is technically possible, so I am fixing this.

**Comment by vjekob** [comment]
This is fixed now. Will be released later today as v1.0.5
