### ISSUE TITLE
Expose API from the extension

### ISSUE THREAD

**Issue by anzwdev** [vjekob/al-objid#8]
Hi

Could you return an object with reservation API from your extension "activate" method? I would like to use it from my extension to suggest and reserve ids in object wizards. If you want, I can create a pull request, but we would need to discuss how you would like to do it first (file names, api structure).

It would probably be better if that API class is just a container for other API objects as it will be easier to extend it later, when your extension gets more functionality, i.e. something like this:

```typescript
class API {
  backendAPI: BackendAPI;
}

class BackendAPI {
  async getNextNo(uri: vscode.Uri, type: string, commit: boolean): Promise<NextObjectIdInfo | undefined>
  async getMultipleNextNos(uri: vscode.Uri, type: string, noOfIds: integer, commit: boolean): Promise<NextObjectIdInfo[] | undefined>
  ... and maybe some other backed functions here ...
}
```

**Comment by vjekob** [comment]
Hi,

Thanks for the suggestion! This is absolutely an interesting thing, and I'd say go ahead and do a PR. There are some back-end changes I'd like to have in place first. Right now, back end can issue only 1 new number per call, and to get - say - 100 nubers, you'd have to place 100 calls. And this will immediately ban your IP for exceeding rate limit.

I would like to change the back end to be able to create more than one new ID, and that's something I'd like to do myself. I hope you understand why I'd prefer keeping back end API totally under my control.

When I am done with that, I am more than fine with you doing a PR and exposing any API from Ninja that you may need.

**Comment by anzwdev** [comment]
Hi

Yes, I understand why you want to keep back end api under your control and I don't want to do any changes there myself. I am fine with just a single id reservation for now. It would be good to have "getMultipleNextNos" function, but it is not necessary.

I also understand that it is very early version of your extension and you will be changing a lot, so I will play with it but I will wait with my PR.

**Comment by vjekob** [comment]
Thanks @anzwdev  for the contribution! 😊

Closed in https://github.com/vjekob/al-objid/pull/55
