### ISSUE TITLE
DevOps idea: let people check a repo

### ISSUE THREAD

**Issue by waldo1001** [vjekob/al-objid#9]
From DevOps, it might be interesting to be able to build a test whether this person (the one that is running a PR) is using Ninja or not.  As such: all IDs in his repo should be reserved.  If not: error.

So .. would it be possible to call the backend, and check if an ID (of the added(/changed) is reserved or not?  Or any other way?  

Think about it .. ;-)

**Comment by vjekob** [comment]
This API is already there, in fact! It's called `getConsumption` and you can test it yourself already. There is an example in `backend/getConsumption_v1/test.http`.

Hope this helps. If not, let me know and I'll reopen the issue.
